#!/usr/bin/env bash
# crosscheck-agent interactive setup
# Walks the user through populating .env and crosscheck.config.json.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BOLD=$(tput bold 2>/dev/null || true)
DIM=$(tput dim 2>/dev/null || true)
RESET=$(tput sgr0 2>/dev/null || true)

say() { printf "%s\n" "$*"; }
hr()  { printf '%s\n' "------------------------------------------------------------"; }

say "${BOLD}crosscheck-agent setup${RESET}"
hr
say "This wizard will create .env and crosscheck.config.json in:"
say "  ${DIM}$ROOT${RESET}"
hr

# ------------------------------------------------------------
# .env
# ------------------------------------------------------------
ENV_FILE="$ROOT/.env"
if [[ -f "$ENV_FILE" ]]; then
  read -r -p "A .env already exists. Overwrite? [y/N] " ans
  if [[ "${ans:-N}" != [yY]* ]]; then
    say "Keeping existing .env. Skipping key prompts."
    SKIP_KEYS=1
  fi
fi

prompt_key() {
  local name="$1" url="$2" default_model="$3" model_var="$4"
  local val=""
  say ""
  say "${BOLD}$name${RESET}  ${DIM}($url)${RESET}"
  read -r -s -p "  API key (leave blank to skip): " val
  echo
  if [[ -n "$val" ]]; then
    printf '%s=%s\n' "$name" "$val" >> "$ENV_FILE"
    printf '%s=%s\n' "$model_var" "$default_model" >> "$ENV_FILE"
  fi
}

if [[ "${SKIP_KEYS:-0}" != "1" ]]; then
  : > "$ENV_FILE"
  printf '# Generated by crosscheck-agent setup on %s\n' "$(date -u +%FT%TZ)" >> "$ENV_FILE"
  prompt_key "ANTHROPIC_API_KEY" "https://console.anthropic.com/"        "claude-opus-4-5"           "ANTHROPIC_MODEL"
  prompt_key "OPENAI_API_KEY"    "https://platform.openai.com/"          "gpt-5"                     "OPENAI_MODEL"
  prompt_key "XAI_API_KEY"       "https://console.x.ai/"                 "grok-4-latest"             "XAI_MODEL"
  prompt_key "GEMINI_API_KEY"    "https://aistudio.google.com/apikey"    "gemini-2.5-pro"            "GEMINI_MODEL"
  prompt_key "MISTRAL_API_KEY"   "https://console.mistral.ai/"           "mistral-large-latest"      "MISTRAL_MODEL"
  prompt_key "GROQ_API_KEY"      "https://console.groq.com/keys"         "llama-3.3-70b-versatile"   "GROQ_MODEL"
  prompt_key "DEEPSEEK_API_KEY"  "https://platform.deepseek.com/"        "deepseek-chat"             "DEEPSEEK_MODEL"
  chmod 600 "$ENV_FILE" || true
  say ""
  say "Wrote $ENV_FILE (chmod 600)."
fi

# ------------------------------------------------------------
# crosscheck.config.json
# ------------------------------------------------------------
hr
say "${BOLD}Runtime limits${RESET}"
read -r -p "  Max unsupervised discussion rounds between LLMs [3]: " rounds
read -r -p "  Token cap per discussion [8000]: " tokens
read -r -p "  Max wall-clock seconds per discussion [120]: " seconds
read -r -p "  Comma-separated providers to use [anthropic,openai,xai]: " providers
read -r -p "  Moderator provider (synthesises the final answer) [anthropic]: " moderator

rounds=${rounds:-3}
tokens=${tokens:-8000}
seconds=${seconds:-120}
providers=${providers:-anthropic,openai,xai}
moderator=${moderator:-anthropic}

# Convert comma-separated list into a JSON array.
providers_json=$(printf '%s' "$providers" | awk -F',' '{
  printf "["
  for (i=1;i<=NF;i++) {
    gsub(/^[ \t]+|[ \t]+$/, "", $i)
    printf "%s\"%s\"", (i>1?",":""), $i
  }
  printf "]"
}')

cat > "$ROOT/crosscheck.config.json" <<EOF
{
  "max_rounds": $rounds,
  "token_cap": $tokens,
  "max_time_seconds": $seconds,
  "providers": $providers_json,
  "moderator": "$moderator",
  "temperature": 0.4,
  "log_transcripts": true,
  "transcript_dir": ".crosscheck/transcripts"
}
EOF

say ""
say "Wrote $ROOT/crosscheck.config.json"
hr
say "${BOLD}Done.${RESET}"
say "Next steps:"
say "  1. Pick a runtime and register it with Claude Code:"
say "       Python      : servers/python/README.md"
say "       TypeScript  : servers/typescript/README.md"
say "       Rust        : servers/rust/README.md"
say "       Perl        : servers/perl/README.md"
say "  2. Tune limits anytime with:"
say "       scripts/crosscheck config set max_rounds 5"
say "  3. Inside Claude Code, try:    /mcp  and call the 'confer' tool."
